import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { TRPCReactProvider } from "@/trpc/react";
import { Toaster } from "@/components/ui/sonner";
import { Navbar } from "@/components/nav-bar";


export const metadata: Metadata = {
  title: "Codoo",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${geist.variable} dark`}>
        <body>
          <TRPCReactProvider>
              <Navbar />
              {children}
              <Toaster
                toastOptions={{
                  style: {
                    borderRadius: "0px",
                    fontSize: "11px",
                  },
                }}
              />
          </TRPCReactProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
